db:
  image: postgres:10
  volumes:
    - /var/lib/postgresql/data

backend: &backend
  build: .
  volumes:
    - .:/app
    - ./vendor/bundle:/usr/local/bundle
  links:
    - db
  ports:
    - 3000:3000
  env_file: docker/rails/development.env

test:
  <<: *backend
  command: ["bundle", "exec", "guard"]
  ports: []
  env_file: docker/rails/test.env
